# Generated by Django 5.2.6 on 2025-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_image_large_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image_large",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image_medium",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image_small",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/avatars/"
            ),
        ),
    ]
